In [1]:
import numpy as np

In [2]:
x = np.array(12)

In [3]:
x

array(12)

In [4]:
x.ndim

0

In [5]:
x = np.array([[1,4],[2,3]])

In [6]:
x.shape

(2, 2)

In [7]:
y = np.array([[-3,4],[-3,1]])

In [8]:
y.shape

(2, 2)

In [9]:
x

array([[1, 4],
       [2, 3]])

In [10]:
z = x + y

In [11]:
z

array([[-2,  8],
       [-1,  4]])

In [12]:
z = np.maximum(z, 0.)

In [13]:
z

array([[ 0.,  8.],
       [ 0.,  4.]])

In [14]:
x

array([[1, 4],
       [2, 3]])

In [15]:
y

array([[-3,  4],
       [-3,  1]])

In [16]:
z = np.dot(x,y)

In [17]:
z

array([[-15,   8],
       [-15,  11]])

In [18]:
# Lo anterior era Numpy
# A ver Keras
from keras import backend as K

Using TensorFlow backend.


In [23]:
z = K.dot(K.variable(x),K.variable(y))

In [28]:
z

<tf.Tensor 'MatMul:0' shape=(2, 2) dtype=float32>

In [2]:
# Algunas pruebas con matrices con numpy
from numpy import *

In [3]:
random.rand(4,4)

array([[ 0.1815529 ,  0.03699485,  0.71968495,  0.85539866],
       [ 0.40513204,  0.73121055,  0.28545478,  0.37214009],
       [ 0.19882582,  0.9004501 ,  0.94259986,  0.8796585 ],
       [ 0.45072458,  0.67086109,  0.50835433,  0.74040695]])

In [4]:
randmat = mat(random.rand(4,4))

In [5]:
randmat

matrix([[ 0.53940408,  0.06576827,  0.05301721,  0.15633317],
        [ 0.22262244,  0.47075145,  0.12684714,  0.96659371],
        [ 0.06695623,  0.98307288,  0.5290978 ,  0.02618786],
        [ 0.95690985,  0.20963044,  0.48137578,  0.54460399]])

In [6]:
randmat.I

matrix([[ 2.31633108, -0.26193697,  0.0132548 , -0.20065932],
        [ 2.23568101,  0.41483289,  0.97283273, -1.42481947],
        [-4.39531312, -0.78692267,  0.10507629,  2.6533335 ],
        [-1.0455111 ,  0.99612561, -0.49063206,  0.39193234]])

In [7]:
invrandmat = randmat.I

In [8]:
randmat*invrandmat

matrix([[  1.00000000e+00,   1.84828644e-16,  -6.15307544e-17,
          -8.46203794e-17],
        [ -1.52509009e-16,   1.00000000e+00,  -2.46516838e-17,
          -5.69269876e-17],
        [ -2.11138139e-16,  -4.72270462e-17,   1.00000000e+00,
           1.22023279e-16],
        [  3.55726009e-16,  -1.24181153e-16,  -1.35471591e-17,
           1.00000000e+00]])

In [10]:
(randmat*invrandmat) - eye(4)

matrix([[ -3.33066907e-16,   1.84828644e-16,  -6.15307544e-17,
          -8.46203794e-17],
        [ -1.52509009e-16,   0.00000000e+00,  -2.46516838e-17,
          -5.69269876e-17],
        [ -2.11138139e-16,  -4.72270462e-17,   2.22044605e-16,
           1.22023279e-16],
        [  3.55726009e-16,  -1.24181153e-16,  -1.35471591e-17,
           0.00000000e+00]])