In [1]:
import numpy as np

In [2]:
x = np.array(12)

In [3]:
x

array(12)

In [4]:
x.ndim

0

In [5]:
x = np.array([[1,4],[2,3]])

In [6]:
x.shape

(2, 2)

In [7]:
y = np.array([[-3,4],[-3,1]])

In [8]:
y.shape

(2, 2)

In [9]:
x

array([[1, 4],
       [2, 3]])

In [10]:
z = x + y

In [11]:
z

array([[-2,  8],
       [-1,  4]])

In [12]:
z = np.maximum(z, 0.)

In [13]:
z

array([[ 0.,  8.],
       [ 0.,  4.]])

In [14]:
x

array([[1, 4],
       [2, 3]])

In [15]:
y

array([[-3,  4],
       [-3,  1]])

In [16]:
z = np.dot(x,y)

In [17]:
z

array([[-15,   8],
       [-15,  11]])

In [18]:
# Lo anterior era Numpy
# A ver Keras
from keras import backend as K

Using TensorFlow backend.


In [23]:
z = K.dot(K.variable(x),K.variable(y))

In [28]:
z

<tf.Tensor 'MatMul:0' shape=(2, 2) dtype=float32>